name: container workflow test
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    container: python:latest
    steps:
        - name: Checkout Project
          uses: actions/checkout@v2
        - name: python test
          run: |
            python -v
            import os
            print(os.getenv('test_username'))
            print(os.getenv('test_password'))
            print("test")
          env:
            test_username: "test_username"
            test_password: "test_password"
