name: container workflow test
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    container: cipz/instagram_bots:latest
    steps:
        - name: Checkout Project
          uses: actions/checkout@v2
        - name: python test
          env:
            test_username: "test_username"
            test_password: "test_password"
          run: |
            apt-get update
            apt-get install python3 -y
            python3 --version
            touch test.py
            echo "import os" >> test.py
            echo "print(os.getenv('soy uno username'))" >> test.py
            echo "print(os.getenv('soy la password por el username'))" >> test.py
            echo "print('test')" >> test.py
            python3 -u test.py
            

